DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  NAME: nutrition5k
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL:
  HEIGHT: 480
  WIDTH: 640
MODEL:
  MASK_WEIGHT: 0.5
  NAME: openseed
  PRETRAINED: ''
SAVE_PATH: models/noisy/fpnopenseed_wrot_fc2-3_nodrop_autoattn_150ep_mltscl.pt
TITLE:
- fpn openseed with aug+rotate fc 2-3 no dropout freeze auto attention 150ep multi
  scale
TRAIN:
  BATCH_SIZE: 32
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LOSS: multi
  LR: 5.0e-05
  NOISE_REMOVAL_EPOCHS: 10
  NUM_EPOCHS: 150
  REMOVE_RATE: 0.03
  SEED: 12345
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.0001
