DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL: {}
MODEL:
  NAME: resnet50
  PRETRAINED: microsoft/resnet-50
SAVE_PATH: models/fpn.pt
TITLE:
- simple fpn test
TRAIN:
  BATCH_SIZE: 128
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LR: 0.0001
  NUM_EPOCHS: 100
  SEED: 12345
  WEIGHT_DECAY: 1.0e-05
