DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL: {}
MODEL:
  NAME: inceptionv2
  PRETRAINED: inception_resnet_v2
SAVE_PATH: models/inceptionv2_noaug_fc3.pt
TITLE:
- inceptionv2 no aug fc 3 test
TRAIN:
  BATCH_SIZE: 128
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LR: 0.001
  NUM_EPOCHS: 100
  SEED: 12345
  WEIGHT_DECAY: 0.0001
