DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  NAME: nutrition5k
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL:
  HEIGHT: 480
  WIDTH: 640
MODEL:
  DROPOUT_RATE: 0.1
  MASK_WEIGHT: 0.8
  NAME: swin
  PRETRAINED: microsoft/swin-tiny-patch4-window7-224
SAVE_PATH: models/swin/mask_lp/fpnswin_mask0.8_lp0.8_1drop1_warmup_150ep_mltscl.pt
TITLE:
- fpn openseed swin mask 0.8 lossp=0.8 with aug+rotate fc 0.1 dropout 1 layers with
  warmup 150ep multi scale
TRAIN:
  BATCH_SIZE: 16
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LOSS: multi
  LP: 0.8
  LR: 5.0e-05
  NOISE_REMOVAL_EPOCHS: 20
  NUM_EPOCHS: 150
  REMOVAL_WEIGHT: 0.1
  REMOVE_RATE: 0.03
  SCHEDULER_WARMUP: 20
  SEED: 12345
  TRAINER: mask_lp
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.0001
