DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  NAME: nutrition5k
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL:
  HEIGHT: 480
  WIDTH: 640
MODEL:
  DECODER:
    MLP_RATIO: 4.0
    NUM_HEADS: 8
    NUM_LAYERS: 4
  DROPOUT_RATE: 0.2
  MASK_DIM: 12
  MASK_WEIGHT: 1.0
  NAME: swin
  PRETRAINED: microsoft/swin-tiny-patch4-window7-224
SAVE_PATH: models/cross-swin-cls/ablation/no_mask_no_decoder_no_lp.pt
TITLE:
- null
TRAIN:
  BATCH_SIZE: 8
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LOSS: multi
  LP: 0.8
  LR: 5.0e-05
  NOISE_REMOVAL_EPOCHS: 20
  NUM_EPOCHS: 150
  REMOVAL_WEIGHT: 0.1
  REMOVE_RATE: 0.03
  SCHEDULER_WARMUP: 15
  SEED: 12345
  TRAINER: mask
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 1.0e-05
