DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  NAME: nutrition5k
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL:
  HEIGHT: 480
  WIDTH: 640
MODEL:
  MASK_WEIGHT: 0.5
  NAME: swin
  PRETRAINED: microsoft/swin-tiny-patch4-window7-224
SAVE_PATH: models/swin/fpnswin_wrot_fc3_drop1_attninit_warmup_150ep_mltscl.pt
TITLE:
- fpn openseed swin with aug+rotate fc 3 no dropout 1 layer freeze new attn initialize with warmup
  150ep multi scale
TRAIN:
  BATCH_SIZE: 16
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LOSS: multi
  LR: 5.0e-05
  NUM_EPOCHS: 150
  SEED: 12345
  WEIGHT_DECAY: 0.0001
