DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL: {}
MODEL:
  NAME: resnet101
  PRETRAINED: microsoft/resnet-101
SAVE_PATH: models/fpn_resnet101_waug_fc3_nodrop_attninit_warmup_smaller_150ep_mltscl.pt
TITLE:
- fpn with aug fc 3 no dropout freeze smaller new attn initialize with warmup 150ep multi scale
TRAIN:
  BATCH_SIZE: 32
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LR: 0.0001
  NUM_EPOCHS: 150
  SEED: 12345
  WEIGHT_DECAY: 0.0001
