DATA:
  IMGS_DIR: /srv/datasets2/nutrition5k_dataset/imagery/realsense_overhead
  METADATAS_PATH: /srv/datasets2/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv
  NAME: nutrition5k
  SPLITS_TEST_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_test_ids.txt
  SPLITS_TRAIN_PATH: /srv/datasets2/nutrition5k_dataset/dish_ids/splits/depth_train_ids.txt
EVAL:
  HEIGHT: 480
  WIDTH: 640
MODEL:
  DECODER:
    MLP_RATIO: 4.0
    NUM_HEADS: 8
    NUM_LAYERS: 4
  DROPOUT_RATE: 0.2
  MASK_DIM: 12
  MASK_WEIGHT: 0.8
  NAME: cross-swin-cls
  PRETRAINED: microsoft/swin-tiny-patch4-window7-224
SAVE_PATH: models/cross-swin-cls/grid-search/lr1e-4_lp0.8_mw0.8.pt
TITLE:
- fpn openseed cross-attention swin with CLS token mask 0.8 lossp=0.8 modified loss
  with aug+rotate fc 0.1 dropout 1 layers with warmup 150ep multi scale with attn
  drop
TRAIN:
  BATCH_SIZE: 8
  CKPT: null
  FINETUNE: false
  LAYERS: 1
  LOSS: multi
  LP: 0.8
  LR: 0.0001
  NOISE_REMOVAL_EPOCHS: 20
  NUM_EPOCHS: 150
  REMOVAL_WEIGHT: 0.1
  REMOVE_RATE: 0.03
  SCHEDULER_WARMUP: 15
  SEED: 12345
  TRAINER: mask_lp
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.0001
