name: ci python-project-template
env:
  PROJECT_NAME: python-project-template
on: [push]
jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Conda
        run: |
          curl -sSL \
          "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" -o ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda init bash
      - name: Setup python3.10
        run: |
          conda create -n nutrition5k python=3.10
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          conda activate nutrition5k
      - name: Install Conda Packages
        run: |
          conda update conda -y -n nutrition5k
          conda install -c conda-forge --file requirements.txt -y -n nutrition5k
      - name: Install Detectron2
        run: |
          python3 -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Packages
        run: |
          poetry config --local virtualenvs.in-project true      
          poetry install
      - name: Run Lint
        run: |
          poetry run pre-commit run --all-files
      - name: Run Test
        run: |
          poetry run pytest --no-header -v
